- frontend/components/SearchPanelComponents/StandardSearch/ResultTable/ResultRow.js
- frontend/package.json
- frontend/redux/actions.js
- frontend/yarn.lock
Fixed bug where link is navigated to when checkbox is clicked on in search results table.
> fixed event propogation bug

- frontend/.eslintrc.js
- frontend/components/Footer.js
- frontend/components/Navbar.js
- frontend/components/NavbarComponents/Profile.js
- frontend/components/NavbarComponents/ProfileMenu.js
- frontend/components/TopLevel.js
- frontend/pages/login.js
- frontend/redux/actions.js
- frontend/redux/reducers.js
- frontend/redux/types.js
- frontend/styles/navbar.module.css
Users now stay logged in after refreshing/closing the page, and are able to sign out. Added profile menu (with options like view profile, admin settings, and sign out). Added keypress actions (such as when enter is pressed on login form). Added some minor styling tweaks. I plan on going back later and adding more icons/styling for the profile menu buttons.
> Store Login Credentials

- FrontendTest.yml
Tests if frontend can build and passes tests on different node versions.
> Adding workflow

- frontend/components/Navbar.js
Check to see if status checks run before being able to merge branch.
> Testing status checks

- frontend/Dockerfile
- frontend/next.config.js
- frontend/package.json
> changed port to 3333

- frontend/.env.production
- frontend/components/Navbar.js
- frontend/components/SearchComponents/NavbarSearch/NavbarSearch.js
- frontend/components/SearchComponents/NavbarSearch/SearchBar.js
- frontend/components/SearchComponents/SearchHeader/SearchHeader.js
- frontend/components/SearchComponents/SearchHeader/SearchTypeButton.js
- frontend/components/SearchComponents/StandardSearch/ResultTable/Navigation.js
- frontend/components/SearchComponents/StandardSearch/ResultTable/ResultTable.js
- frontend/pages/index.js
- frontend/pages/root-collections.js
- frontend/pages/search.js
- frontend/styles/basket.module.css
- frontend/styles/navbar.module.css
- frontend/styles/resulttable.module.css
- frontend/styles/searchheader.module.css
Display root collections page is finished. Updated home page to allow users to view public collections. Removed "Shared with me" page, as shared designs will now be in the manage submissions page.
> Root collections

- frontend/.env.production
- frontend/pages/submissions.js
- frontend/styles/navbar.module.css
- frontend/styles/submissions.module.css
Changed the url that sbh2 frontend fetches from
> Change backend url

- frontend/pages/_app.js
- frontend/pages/root-collections.js
Fixed bug where font awesome icons are too large initially when rendering on the server side
> Fontawesomecss

- frontend/components/SearchComponents/StandardSearch/ResultTable/ResultTable.js
- frontend/components/SearchComponents/StandardSearch/ResultTable/TableButtons.js
- frontend/pages/index.js
- frontend/pages/submissions.js
- frontend/styles/home.module.css
- frontend/styles/submissions.module.css
Made submissions page with table that displays both the users submissions and submissions shared with the user. Added manage submissions button. I plan on adding button functionality soon.
> Submissions

- frontend/components/Footer.js
- frontend/components/SubmitComponents/OverwriteObjects.js
- frontend/pages/login.js
- frontend/pages/submit.js
- frontend/styles/submit.module.css
Create account links to sbh dev for now so people can create accounts and try out SBH2
> New Account Link to sbh dev

- frontend/components/Message.js
- frontend/components/SubmitComponents/OverwriteObjects.js
- frontend/components/SubmitComponents/SubmitButton.js
- frontend/pages/submit.js
- frontend/redux/actions.js
- frontend/styles/message.module.css
- frontend/styles/submit.module.css
Users can now check to overwrite collection objects. The first time they check to overwrite collections, they are prompted with a warning message, which they can choose to disable in the future.
> Overwrite Merge

- frontend/components/SubmitComponents/OverwriteObjects.js
- frontend/styles/message.module.css
Fixed bug where overwrite prompt not displaying on first time submission page is loaded
> Fixed prompt user bug

- frontend/components/NavbarComponents/ProfileMenu.js
- frontend/redux/actions.js
- frontend/redux/reducers.js
- frontend/redux/types.js
- frontend/styles/home.module.css
- frontend/styles/message.module.css
- frontend/styles/navbar.module.css
User profile settings/info is fetched and displayed
> Viewprofile

- frontend/components/LoginComponents/InputField.js
- frontend/components/NavbarComponents/ProfileMenu.js
- frontend/pages/profile.js
- frontend/redux/actions.js
- frontend/styles/globals.css
Profile page where user can update profile information
> Profilepage

- frontend/components/NavbarComponents/Selector.js
- frontend/components/SearchComponents/StandardSearch/ResultTable/TableButtons.js
- frontend/pages/index.js
- frontend/pages/submissions.js
- frontend/styles/navbar.module.css
- frontend/styles/submissions.module.css
Page that the user is on is now reflected in the navigation bar
> Underline page in navbar

- frontend/components/AdminComponents/Content.js
- frontend/components/NavbarComponents/ProfileMenu.js
- frontend/components/TopLevel.js
- frontend/pages/admin/[page].js
still need to fix redirecting bug when navigating to /admin through router
> Admin link does not appear when user is not admin

- frontend/components/SearchComponents/AdvancedSearch/Options.js
- frontend/components/SearchComponents/AdvancedSearch/SelectLoader.js
- frontend/sparql/getPredicates.js
- frontend/styles/advancedsearch.module.css
fixed bugs, added some extra styling
> Advanced predicates

- frontend/components/Reusable/Table/Table.js
- frontend/components/Reusable/Table/TableNav.js
- frontend/components/Viewing/Collection/Members.js
Fixed bugs with paging through collection, added sorting capability to collection
> Pluginsupport

- frontend/Dockerfile
- frontend/components/Viewing/Sections/MemberOfCollections.js
- frontend/components/Viewing/Sections/OtherProperties.js
- frontend/components/Viewing/TypeContents/CollectionContent.js
- frontend/components/Viewing/TypeContents/ComponentContent.js
- frontend/package.json
- frontend/sparql/getMemberOfCollections.js
- frontend/sparql/getOtherProperties.js
- frontend/styles/view.module.css
Added the Member of these Collections section and updated the Dockerfile to remove the argument that was throwing the error.
> Added Member of these Collections section 

- backend/src/main/java/com/synbiohub/sbh3/controllers/PluginController.java
- backend/src/main/java/com/synbiohub/sbh3/services/PluginService.java
Got a fresh commit and only added the two files necessary
> Added The Two Files

- backend/src/main/java/com/synbiohub/sbh3/controllers/SearchController.java
> testing to see if this will go to the correct branch

- backend/README.md
For Issue #244: Updated README.md for backend by adding sections for installing backend and virtuoso from both source and Docker.
> Updated ReadME

- backend/src/main/java/com/synbiohub/sbh3/controllers/SearchController.java
- backend/src/main/java/com/synbiohub/sbh3/services/SearchService.java
Fixed a couple bugs in search, causing things like logging in not working for search and collection not working. Also, set up URL decoder for the future.
> Search bugs

- backend/src/main/resources/config.json
Allows backend to connect to virtuoso when running on docker
> Replace 'localhost' with 'virtuoso'

- backend/src/main/java/com/synbiohub/sbh3/Synbiohub3Application.java
- backend/src/main/java/com/synbiohub/sbh3/security/WebConfiguration.java
- backend/src/main/java/com/synbiohub/sbh3/services/SearchService.java
SearchService: added URL decoding to input searches. Added ability for advanced search to do things like and, or, and not, timeCreated, and objectType.
Main and WebConfiguration: added new Firewall to help with URL decoding with certain symbols that were unable to be put in the URL due to CORS. Still have issues with backslash and single apostrophe.
> Fixed some search bugs related to url encoding

- backend/src/main/java/com/synbiohub/sbh3/controllers/UserController.java
- backend/src/main/java/com/synbiohub/sbh3/security/CustomUserService.java
- backend/src/main/java/com/synbiohub/sbh3/services/UserService.java
Added code for endpoint /profile, POST, so user can now update their profile.
Currently, it is not working as intended in all forms. The user has to enter in both password1 and password2 in order to update the profile. Otherwise, it fails. Also, until I figure out how to extract the password from the authentication, I am not sure how to verify the entered password, is the correct password. Updating the profile should not allow the user to change their password in this manner without some sort of other security check.
This is for issue # 263.
> Implementation of updating user profile endpoint

- backend/src/main/java/com/synbiohub/sbh3/controllers/AdminController.java
- backend/src/main/java/com/synbiohub/sbh3/controllers/DownloadController.java
- backend/src/main/java/com/synbiohub/sbh3/controllers/PluginController.java
- backend/src/main/java/com/synbiohub/sbh3/security/SecurityConfiguration.java
- backend/src/main/java/com/synbiohub/sbh3/services/DownloadService.java
- backend/src/main/resources/config.json
- frontend/components/Viewing/TypeContents/GenericTable.js
AdminController - muted admin/plugins for now as it is already implemented in the PluginController.
DownloadController - changed it from using stars to using PathVariables to use the URI variables 
DownloadService - Fixed some bugs including changing the way the args are set up, and adding offset and sbol2 prefix. Plugins - changed path from /plugins to /admin/plugins 
SecurityConfiguration - currently muted that /admin endpoints are blocked. Need to add in the future that some admin endpoints should still be allowed, even when not logged in as an admin.
Ben, I pushed my changes, including a small change to GenericTable.js, where I just always set it as 0. Can you check that this doesn't affect SBH1?
> Got download and display pages to work for SBH3. 

- frontend/components/Viewing/Shell.js
For easier creation of JSON for people not familiar with code
> display type when no JSON exists for it

- backend/src/main/java/com/synbiohub/sbh3/controllers/AdminController.java
- backend/src/main/java/com/synbiohub/sbh3/controllers/DownloadController.java
- backend/src/main/java/com/synbiohub/sbh3/controllers/SubmitController.java
- backend/src/main/java/com/synbiohub/sbh3/controllers/UserController.java
- backend/src/main/java/com/synbiohub/sbh3/dto/SubmissionDTO.java
- backend/src/main/java/com/synbiohub/sbh3/requests/SubmitRequest.java
- backend/src/main/java/com/synbiohub/sbh3/security/CustomUserService.java
- backend/src/main/java/com/synbiohub/sbh3/services/AdminService.java
- backend/src/main/java/com/synbiohub/sbh3/services/SubmitService.java
- backend/src/main/java/com/synbiohub/sbh3/services/UserService.java
- backend/src/main/java/com/synbiohub/sbh3/utils/ConfigUtil.java
- backend/src/main/java/com/synbiohub/sbh3/utils/ObjectMapperUtils.java
For ObjectMapperUtils, added the builder method
FOr SubmissionDTO and SubmitRequest, created these object classes to represent the objects. For the SubmitController, just mostly made the post mapping request. For the SubmitService, added a lot of methods and helper functions for submission.
> Set up the basic structure for submission.

- tests/add-igem-data/out/18236_BBa_J70591.xml
- tests/add-igem-data/out/27733_BBa_K773001.xml
- tests/add-igem-data/out/27968_BBa_K783051.xml
- tests/add-igem-data/out/32939_BBa_K1325011.xml
- tests/add-igem-data/out/36587_BBa_K1583061.xml
- tests/add-igem-data/out/7717_BBa_J34801.xml
- tests/add-igem-data/upload1.js
- tests/add-igem-data/upload3.js
- tests/test_search.py
root collections test
more data
> Add interesting data anjala

- backend/pom.xml
- backend/src/main/java/com/synbiohub/sbh3/controllers/UserController.java
- backend/src/main/java/com/synbiohub/sbh3/security/auth/TokenController.java
- backend/src/main/java/com/synbiohub/sbh3/security/config/ApplicationConfig.java
- backend/src/main/java/com/synbiohub/sbh3/security/config/SecurityConfig.java
- backend/src/main/java/com/synbiohub/sbh3/security/customsecurity/AuthenticationResponse.java
- backend/src/main/java/com/synbiohub/sbh3/security/customsecurity/JwtAuthenticationFilter.java
- backend/src/main/java/com/synbiohub/sbh3/security/customsecurity/JwtService.java
- backend/src/main/java/com/synbiohub/sbh3/security/model/User.java
- backend/src/main/java/com/synbiohub/sbh3/services/UserService.java
- tests/test_user.py
Added custom configurations for jwt tokens. Actually added register so that it creates and saves a new user. New users are all currently being set to admin role. Turned on login test and login now works (local and local docker)
> Login should now work

- backend/src/main/java/com/synbiohub/sbh3/controllers/UserController.java
- backend/src/main/java/com/synbiohub/sbh3/security/model/User.java
- backend/src/main/java/com/synbiohub/sbh3/services/UserService.java
- tests/first_time_setup.py
- tests/test_user.py
Made User cloneable. Turned on and tested post request for profile; only updates the fields name, email, and affiliation
> Post Request for profile

- tests/first_time_setup.py
- tests/test_functions.py
> /setup test using json post function

- backend/src/main/java/com/synbiohub/sbh3/controllers/AdminController.java
- backend/src/main/java/com/synbiohub/sbh3/controllers/UserController.java
- backend/src/main/java/com/synbiohub/sbh3/security/config/SecurityConfig.java
- backend/src/main/java/com/synbiohub/sbh3/services/AdminService.java
- backend/src/main/java/com/synbiohub/sbh3/services/UserService.java
Tried to turn on logout endpoint, still not working properly. Added theme parameters to config local. Need to still edit on formatting. Cleaned up security config a little. Added an error message to login failure.
> Some bug fixes to theme and login. Fixing logout (still in progress)

- tests/test_functions.py
- tests/test_user.py
> update login test, add test for bad email

- frontend/.env.development
- frontend/next.config.js
- frontend/pages/[...view].js
Fixes issue with docker-composed frontend running locally
> added extra environment variable for SSR

- backend/src/main/java/com/synbiohub/sbh3/controllers/UserController.java
- backend/src/main/java/com/synbiohub/sbh3/services/DownloadService.java
- backend/src/main/java/com/synbiohub/sbh3/services/SearchService.java
- backend/src/main/java/com/synbiohub/sbh3/services/UserService.java
- tests/first_time_setup.py
Added a small change to download. Still has issues and not recognizing query correctly.
Minor change to tests for the time being so that setup is not being compared. SBH1 is returning the HTML for /setup. Added an unlisted endpoint for logging out everyone from SBH3. Changed login, so that bad password is recognized as password issue.
> Still fixing download issues. Bug fixes for user endpoints.

- tests/first_time_setup.py
- tests/test_admin.py
- tests/test_functions.py
- tests/test_search.py
- tests/test_twins.py
- tests/test_user.py
error handling, updates admin, search, twins tests to match updated functions
> updated JSON compare funcs

- backend/src/main/java/com/synbiohub/sbh3/controllers/AdminController.java
- backend/src/main/java/com/synbiohub/sbh3/services/AdminService.java
- backend/src/main/java/com/synbiohub/sbh3/services/SearchService.java
- backend/src/main/java/com/synbiohub/sbh3/sparql/GetDatabaseStatus.sparql
- backend/src/main/resources/application.yml
Will say Alive if virtuoso is connected. Dead if it's not connected. Phrase can be changed anytime.
> Implemented admin/virtuoso endpoint

- backend/src/main/java/com/synbiohub/sbh3/controllers/AdminController.java
- backend/src/main/java/com/synbiohub/sbh3/controllers/UserController.java
- backend/src/main/java/com/synbiohub/sbh3/services/AdminService.java
- backend/src/main/java/com/synbiohub/sbh3/services/UserService.java
Minor syntax changes with user endpoints
Admin administrator email endpoint should be done
Admin get remotes is done, just a config get
Admin post updateExplorerIndex needs to be looked at more, but basic code is started.
> Minor changes and a couple of admin endpoints added

- backend/src/main/java/com/synbiohub/sbh3/controllers/AdminController.java
- backend/src/main/java/com/synbiohub/sbh3/services/AdminService.java
- backend/src/main/java/com/synbiohub/sbh3/utils/ConfigUtil.java
- tests/test_admin.py
> admin/savePlugin, admin/deletePlugin

- frontend/components/Viewing/PageJSON/MasterJSON.js
- frontend/components/Viewing/PageJSON/Types/FunctionalComponent.json
- frontend/components/Viewing/PageJSON/Types/ModuleDefinition.json
updated module definition and made functional component. mapsTo also tested and mostly works. Overall working, but a lot of minor bugs to fix and placement of objects to change
> module definition and functional component

- frontend/components/Viewing/PageJSON/Fetching/buildQuery.js
- frontend/components/Viewing/PageJSON/Types/Component.json
- frontend/components/Viewing/PageJSON/Types/ComponentDefinition.json
- frontend/components/Viewing/PageJSON/Types/Experiment.json
- frontend/components/Viewing/PageJSON/Types/ExperimentalData.json
- frontend/components/Viewing/PageJSON/Types/FunctionalComponent.json
- frontend/components/Viewing/PageJSON/Types/Interaction.json
- frontend/components/Viewing/PageJSON/Types/MapsTo.json
- frontend/components/Viewing/PageJSON/Types/Module.json
- frontend/components/Viewing/PageJSON/Types/ModuleDefinition.json
made some major changes to the json pages. edited component, component definiton, experiment, experimental data, functional component, interaction, mapsto, module, and module definitoin
> json pages 3

- frontend/components/Viewing/PageJSON/Types/Attachment.json
- frontend/components/Viewing/PageJSON/Types/CombinatorialDerivation.json
- frontend/components/Viewing/PageJSON/Types/ComponentDefinition.json
- frontend/components/Viewing/PageJSON/Types/FunctionalComponent.json
- frontend/components/Viewing/PageJSON/Types/Model.json
- frontend/components/Viewing/PageJSON/Types/Participation.json
- frontend/components/Viewing/PageJSON/Types/Sequence.json
- frontend/components/Viewing/PageJSON/Types/SequenceAnnotation.json
- frontend/components/Viewing/PageJSON/Types/SequenceConstraint.json
edited several more json pages including attachment, combinatorial derivation, component definition, functional component, model, participation, sequence, sequence annotation, and sequence constraint
> more json pages

- frontend/components/Submit/SubmissionStatusPanel.js
- frontend/components/Viewing/PageJSON/Rendering/RowWrapper.js
- frontend/components/Viewing/PageJSON/Rendering/SectionRenderer.js
- frontend/components/Viewing/Shell.js
- frontend/components/Viewing/SidePanel.js
- frontend/components/Viewing/ViewHeader.js
fixed issue with submission not working properly due to wrong url, fixed associated link issue, all links should be working correctly from this point on
> fixed issue with urls

- frontend/components/Admin/Mail.js
- frontend/components/Admin/Plugins.js
- frontend/components/Admin/Registries.js
- frontend/components/Admin/Remotes.js
- frontend/components/Admin/Sparql.js
- frontend/components/Admin/Users.js
- frontend/components/Viewing/Modals/AddToCollectionModal.js
- frontend/components/Viewing/Modals/ShareModal.js
- frontend/components/Viewing/Sections/Attachments/UploadAttachments.js
- frontend/components/Viewing/Sections/Details/EditSection.js
- frontend/pages/root-collections.js
- frontend/pages/sparql.js
- frontend/redux/actions.js
> changed all uses of fetch() to axios()

- frontend/components/Viewing/PageJSON/Rendering/RowWrapper.js
- frontend/components/Viewing/PageJSON/Rendering/SectionRenderer.js
- frontend/components/Viewing/PageJSON/Rendering/createRenderingObject.js
- frontend/components/Viewing/PageJSON/Types/ComponentDefinition.json
- frontend/components/Viewing/PageJSON/Types/SequenceAnnotation.json
- frontend/components/Viewing/SidePanel.js
- frontend/sparql/getMetadata.js
This is actually jsonpage23, just had an issue so it was restored from 22
> Restorejsonpage22

- frontend/components/Viewing/MetadataInfo.js
- frontend/components/Viewing/Sections/OtherProperties.js
- frontend/components/Viewing/Shell.js
- frontend/components/Viewing/ViewHeader.js
- frontend/styles/view.module.css
> Annotationedit

- .gitignore
- frontend/components/Basket/AddToCollectionButton.js
- frontend/components/Basket/Basket.js
- frontend/components/Basket/BasketItem.js
- frontend/components/Basket/CreateCollection.js
- frontend/components/Search/NavbarSearch/NavbarSearch.js
- frontend/components/Viewing/Modals/DeleteModal.js
- frontend/components/Viewing/SidePanelTools.js
- frontend/redux/actions.js
- frontend/styles/basket.module.css
- frontend/styles/navbar.module.css
- frontend/styles/submit.module.css
- frontend/styles/view.module.css
Closes #865 
Note that that issue was actually mainly being caused by the login token issue. However this closes a lot of related unlogged issues including deleted collections appearing in basket, failing to create a collection from basket, urls pointing to the backend, and collections not being able to be deleted from the collection page. Also a lot of minor formatting issues
> Basket errors
